sbatch	runBIL_SEA.sh
sleep 30
sbatch	runBOI_PDX.sh
sleep 30
sbatch	runBZN_PDX.sh
sleep 30
sbatch	runCHS_SEA.sh
sleep 30
sbatch	runCMH_SEA.sh
sleep 30
sbatch	runFAT_PDX.sh
sleep 30
sbatch	runGEG_PDX.sh
sleep 30
sbatch	runGTF_SEA.sh
sleep 30
sbatch	runHLN_SEA.sh
sleep 30
sbatch	runICT_SEA.sh
sleep 30
sbatch	runMSO_PDX.sh
sleep 30
sbatch	runOKC_SEA.sh
sleep 30
sbatch	runPDX_RNO.sh
sleep 30
sbatch	runPDX_SBA.sh
sleep 30
sbatch	runPDX_STS.sh
sleep 30
sbatch	runSBA_SEA.sh
sleep 30
sbatch	runSEA_STS.sh
sleep 30
sbatch	runSEA_SUN.sh
sleep 30
sbatch	runBOS_SAN.sh
sleep 30
sbatch	runBOS_MCI.sh
sleep 30
sbatch	runBOS_JAX.sh
sleep 30
sbatch	runAUS_BOS.sh
