sbatch	robustEstimBIL_SEA.sh
sleep 30
sbatch	robustEstimBOI_PDX.sh
sleep 30
sbatch	robustEstimBZN_PDX.sh
sleep 30
sbatch	robustEstimCHS_SEA.sh
sleep 30
sbatch	robustEstimCMH_SEA.sh
sleep 30
sbatch	robustEstimFAT_PDX.sh
sleep 30
sbatch	robustEstimGEG_PDX.sh
sleep 30
sbatch	robustEstimGTF_SEA.sh
sleep 30
sbatch	robustEstimHLN_SEA.sh
sleep 30
sbatch	robustEstimICT_SEA.sh
sleep 30
#sbatch	robustEstimLIH_PDX.sh
#sleep 30
sbatch	robustEstimMSO_PDX.sh
sleep 30
sbatch	robustEstimOKC_SEA.sh
sleep 30
sbatch	robustEstimOMA_SEA.sh
sleep 30
#sbatch	robustEstimPDX_PSP.sh
#sleep 30
sbatch	robustEstimPDX_RNO.sh
sleep 30
sbatch	robustEstimPDX_SBA.sh
sleep 30
#sbatch	robustEstimPDX_SMF.sh
#sleep 30
sbatch	robustEstimPDX_STS.sh
sleep 30
sbatch	robustEstimSBA_SEA.sh
sleep 30
sbatch	robustEstimSEA_STS.sh
sleep 30
sbatch	robustEstimSEA_SUN.sh
sleep 30
#sbatch	robustEstimBOS_SEA.sh
#sleep 30
sbatch	robustEstimBOS_SAN.sh
sleep 30
#sbatch	robustEstimBOS_PDX.sh
#sleep 30
sbatch	robustEstimBOS_MCI.sh
sleep 30
sbatch	robustEstimBOS_JAX.sh
sleep 30
sbatch	robustEstimAUS_BOS.sh

