sbatch	calcSEBIL_SEA.sh
sleep 30
sbatch	calcSEBOI_PDX.sh
sleep 30
sbatch	calcSEBZN_PDX.sh
sleep 30
sbatch	calcSECHS_SEA.sh
sleep 30
sbatch	calcSECMH_SEA.sh
sleep 30
sbatch	calcSEFAT_PDX.sh
sleep 30
sbatch	calcSEGEG_PDX.sh
sleep 30
sbatch	calcSEGTF_SEA.sh
sleep 30
sbatch	calcSEHLN_SEA.sh
sleep 30
sbatch	calcSEICT_SEA.sh
sleep 30
#sbatch	calcSELIH_PDX.sh
#sleep 30
sbatch	calcSEMSO_PDX.sh
sleep 30
sbatch	calcSEOKC_SEA.sh
sleep 30
sbatch	calcSEOMA_SEA.sh
sleep 30
#sbatch	calcSEPDX_PSP.sh
#sleep 30
sbatch	calcSEPDX_RNO.sh
sleep 30
sbatch	calcSEPDX_SBA.sh
sleep 30
#sbatch	calcSEPDX_SMF.sh
#sleep 30
sbatch	calcSEPDX_STS.sh
sleep 30
sbatch	calcSESBA_SEA.sh
sleep 30
sbatch	calcSESEA_STS.sh
sleep 30
sbatch	calcSESEA_SUN.sh
sleep 30
#sbatch	calcSEBOS_SEA.sh
#sleep 30
sbatch	calcSEBOS_SAN.sh
sleep 30
#sbatch	calcSEBOS_PDX.sh
#sleep 30
sbatch	calcSEBOS_MCI.sh
sleep 30
sbatch	calcSEBOS_JAX.sh
sleep 30
sbatch	calcSEAUS_BOS.sh

