sbatch	runCFBIL_SEA.sh
sleep 5
sbatch	runCFBOI_PDX.sh
sleep 5
sbatch	runCFBZN_PDX.sh
sleep 5
sbatch	runCFCHS_SEA.sh
sleep 5
sbatch	runCFCMH_SEA.sh
sleep 5
sbatch	runCFFAT_PDX.sh
sleep 5
sbatch	runCFGEG_PDX.sh
sleep 5
sbatch	runCFGTF_SEA.sh
sleep 5
sbatch	runCFHLN_SEA.sh
sleep 5
sbatch	runCFICT_SEA.sh
sleep 5
#sbatch	runCFLIH_PDX.sh
#sleep 5
sbatch	runCFMSO_PDX.sh
sleep 5
#sbatch	runCFOKC_SEA.sh
#sleep 5
sbatch	runCFOMA_SEA.sh
sleep 5
#sbatch	runCFPDX_PSP.sh
#sleep 5
sbatch	runCFPDX_RNO.sh
sleep 5
sbatch	runCFPDX_SBA.sh
sleep 5
#sbatch	runCFPDX_SMF.sh
#sleep 5
sbatch	runCFPDX_STS.sh
sleep 5
sbatch	runCFSBA_SEA.sh
sleep 5
sbatch	runCFSEA_STS.sh
sleep 5
sbatch	runCFSEA_SUN.sh
sleep 5
#sbatch	runCFBOS_SEA.sh
#sleep 5
sbatch	runCFBOS_SAN.sh
sleep 5
#sbatch	runCFBOS_PDX.sh
#sleep 5
sbatch	runCFBOS_MCI.sh
sleep 5
sbatch	runCFBOS_JAX.sh
sleep 5
sbatch	runCFAUS_BOS.sh

