sbatch	runSLCFBIL_SEA.sh
sleep 30
sbatch	runSLCFBOI_PDX.sh
sleep 30
sbatch	runSLCFBZN_PDX.sh
sleep 30
sbatch	runSLCFCHS_SEA.sh
sleep 30
sbatch	runSLCFCMH_SEA.sh
sleep 30
sbatch	runSLCFFAT_PDX.sh
sleep 30
sbatch	runSLCFGEG_PDX.sh
sleep 30
sbatch	runSLCFGTF_SEA.sh
sleep 30
sbatch	runSLCFHLN_SEA.sh
sleep 30
sbatch	runSLCFICT_SEA.sh
sleep 30
#sbatch	runSLCFLIH_PDX.sh
#sleep 30
sbatch	runSLCFMSO_PDX.sh
sleep 30
#sbatch	runSLCFOKC_SEA.sh
#sleep 30
sbatch	runSLCFOMA_SEA.sh
sleep 30
#sbatch	runSLCFPDX_PSP.sh
#sleep 30
sbatch	runSLCFPDX_RNO.sh
sleep 30
sbatch	runSLCFPDX_SBA.sh
sleep 30
#sbatch	runSLCFPDX_SMF.sh
#sleep 30
sbatch	runSLCFPDX_STS.sh
sleep 30
sbatch	runSLCFSBA_SEA.sh
sleep 30
sbatch	runSLCFSEA_STS.sh
sleep 30
sbatch	runSLCFSEA_SUN.sh
sleep 30
#sbatch	runSLCFBOS_SEA.sh
#sleep 30
sbatch	runSLCFBOS_SAN.sh
sleep 30
#sbatch	runSLCFBOS_PDX.sh
#sleep 30
sbatch	runSLCFBOS_MCI.sh
sleep 30
sbatch	runSLCFBOS_JAX.sh
sleep 30
sbatch	runSLCFAUS_BOS.sh

